version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: wisdom_server
    environment:
      - POW_SERVER_HTTP_PORT=8080
      - POW_SERVER_DIFFICULTY=6
      - POW_SERVER_QUOTES_PATH=/app/quotes.txt
      - POW_SERVER_WAIT_SOLVING=5
    networks:
      - wisdom_network

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: wisdom_client
    environment:
      - PROVER_SERVER_ADDR=server:8080
      - PROVER_DIFFICULTY=6
    depends_on:
      - server
    networks:
      - wisdom_network

networks:
  wisdom_network:
    driver: bridge
